project_name: external-dns-scp-webhook

builds:
  - id: webhook
    main: ./cmd/webhook
    binary: webhook
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath

dockers:
  - image_templates:
      - "ghcr.io/z1yoon/external-dns-scp-webhook:{{ .Tag }}-amd64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
    goarch: amd64

  - image_templates:
      - "ghcr.io/z1yoon/external-dns-scp-webhook:{{ .Tag }}-arm64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/z1yoon/external-dns-scp-webhook:{{ .Tag }}"
    image_templates:
      - "ghcr.io/z1yoon/external-dns-scp-webhook:{{ .Tag }}-amd64"
      - "ghcr.io/z1yoon/external-dns-scp-webhook:{{ .Tag }}-arm64"

  - name_template: "ghcr.io/z1yoon/external-dns-scp-webhook:latest"
    image_templates:
      - "ghcr.io/z1yoon/external-dns-scp-webhook:{{ .Tag }}-amd64"
      - "ghcr.io/z1yoon/external-dns-scp-webhook:{{ .Tag }}-arm64"

archives:
  - format: tar.gz

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
